apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qhv1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qhv1
    app.kubernetes.io/part-of: tkrw-pr714-0075-0032-app
  name: devfile-sample-qhv1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-qhv1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-qhv1
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0032-tenant/tkrw-pr714-0075-0032-app/devfile-sample-qhv1@sha256:5fabd3c362d12b35f911f09ca6b489cfeeaa98d288977ac46acdbd72451937c8
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
